version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: 'minio_user'
      MINIO_ROOT_PASSWORD: 'minio_password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data

  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    restart: always
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

#  pgweb:
#    image: sosedoff/pgweb
#    container_name: pgweb
#    restart: always
#    env_file: .env
#    ports:
#      - "8081:8081"
#    environment:
#      DATABASE_URL: postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgresql:5432/$POSTGRES_DB

volumes:
  minio_data:
  postgresql_data:
