server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: create-drop
